// Generated by scripts/build-reader.mjs; edit lib/ sources.
const allowedSuffixes = ['.xhscdn.com', '.xhscdn.net', '.douyinvod.com', '.douyinpic.com', '.byteimg.com'];
export function isAllowedMediaUrl(url) {
    return url.protocol === 'https:' && !url.username && !url.password && (!url.port || url.port === '443') && allowedSuffixes.some(suffix => url.hostname.toLowerCase().endsWith(suffix));
}
