// Generated by scripts/build-reader.mjs; edit lib/ sources.
// A readable title or media address is not a completed content read.
export function hasFullBody(result) {
    return result.resolved === true && result.reasonCode === 'ok' && result.contentStatus === 'body'
        && result.extraction?.textStatus === 'full' && Boolean(result.extraction.pageText?.trim());
}
export const resolutionCacheTtl = (result) => hasFullBody(result) ? 300_000 : 10_000;
