'use client';
import type { ReportV2 } from '@/lib/shared/report';
const labels={supported:'有相关依据',risk:'宣传风险',insufficient:'证据不足',context:'普通表述 / 语境说明'};
export default function EvidenceReport({report,text,onReset,onEdit}:{report:ReportV2;text:string;onReset:()=>void;onEdit?:()=>void}){
 const printReport=()=>{const closed=Array.from(document.querySelectorAll<HTMLDetailsElement>('.report-v2 details:not([open])'));closed.forEach(el=>el.open=true);window.addEventListener('afterprint',()=>closed.forEach(el=>el.open=false),{once:true});window.print();};
 const tone=report.status!=='complete'?'unknown':report.findings.some(f=>f.judgment==='risk')?'risk':report.findings.some(f=>f.judgment==='insufficient')?'warning':'clear';
 const sourceIds=[...new Set(report.findings.flatMap(f=>f.citations))];
 const ingredientTable=(items:ReportV2['ingredients'])=><div className="ingredient-table"><table><thead><tr><th>成分 / INCI</th><th>常见用途</th><th>识别来源</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.cn}</strong><small>{item.inci}</small></td><td>{item.purpose}</td><td>{item.origin==='label'?'用户标记的标签':'内容提及'}<small>“{item.quote}”</small></td></tr>)}</tbody></table></div>;
 return <div className="report-v2">
  <section className={`consumer-result ${tone}`}><span className="result-icon" aria-hidden="true">{tone==='clear'?'✓':tone==='unknown'?'?':'!'}</span><div className="result-copy"><small>{report.status==='complete'?'宣传核验报告':'本次未完成判断'}</small><h1>{report.summary}</h1><p>{report.status==='complete'?`核对了 ${report.findings.length} 处表述 · 引用 ${sourceIds.length} 项资料`:'没有生成可靠结论，不代表内容为真或为假'}{report.cached?' · 缓存报告':''}</p></div><div className="result-actions">{onEdit&&<button type="button" onClick={onEdit}>修改 / 补充内容</button>}<button type="button" onClick={onReset}>检测另一条</button></div></section>
  <p className="scope-caption">分析范围：{report.scope.slice(0,3).join('；')}</p>
  {report.findings.length>0&&<section className="report-findings" aria-label="主要发现">{report.findings.map((f,i)=><article key={i}><span className={`finding-label ${f.judgment}`}>{labels[f.judgment]}</span><blockquote>“{f.quote}”</blockquote><p>{f.reason}</p><details><summary>判断依据{f.citations.length?` · ${f.citations.length}`:''}</summary>{f.citations.length?f.citations.map(id=>{const s=report.sources.find(s=>s.id===id);return s?<div className="source-detail" key={id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} · {s.section} ↗</a><p>{s.text}</p><small>{s.jurisdiction} · {s.version}</small><p className="source-boundary">{s.limitation??'通用资料，不是该产品的检测证明。'}</p></div>:null;}):<p>当前资料不足以核实这项具体宣称。</p>}</details></article>)}</section>}
  <section className="report-ingredients"><h2>内容中的成分{report.ingredients.length?` · ${report.ingredients.length} 项`:''}</h2>{report.ingredients.length?<><p>仅展示识别到的成分；通用用途不等于成品效果或安全评级。</p>{ingredientTable(report.ingredients.slice(0,3))}{report.ingredients.length>3&&<details><summary>展开其余 {report.ingredients.length-3} 项成分</summary>{ingredientTable(report.ingredients.slice(3))}</details>}<details><summary>成分命名来源</summary><a href={report.ingredients[0].source.url} target="_blank" rel="noreferrer">{report.ingredients[0].source.title} ↗</a><p>中文名和用途为人工整理。标签截图未必包含完整配方。</p></details></>:<p>未识别到已收录成分，不代表产品没有其他成分。</p>}</section>
  <details className="report-scope"><summary>查看读取原文与完整分析范围</summary><ul>{report.scope.map((s,i)=><li key={i}>{s}</li>)}</ul><pre>{text||'尚未取得正文、画面文字或口播。'}</pre>{report.status!=='complete'&&report.sources.length>0&&<><h3>已检索到的参考资料（未形成结论）</h3>{report.sources.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} · {s.section} ↗</a></p>)}</>}</details>
  <footer className="report-footer"><p>{report.note}</p><small>报告 v{report.version} · 知识库 {report.kbVersion}{report.model?` · ${report.model}`:''}{report.generatedAt?` · ${new Date(report.generatedAt).toLocaleString('zh-CN')}`:''}</small><button type="button" onClick={printReport}>打印 / 保存 PDF</button></footer>
 </div>;
}
