'use client';
import type { ReportV2 } from '@/lib/shared/report';
const labels={supported:'有相关依据',risk:'宣传风险',insufficient:'证据不足',context:'需结合语境'};
export default function EvidenceReport({report,text,onReset}:{report:ReportV2;text:string;onReset:()=>void}){
 const printReport=()=>{const closed=Array.from(document.querySelectorAll<HTMLDetailsElement>('.report-v2 details:not([open])'));closed.forEach(el=>el.open=true);window.addEventListener('afterprint',()=>closed.forEach(el=>el.open=false),{once:true});window.print();};
 const tone=report.status!=='complete'?'unknown':report.findings.some(f=>f.judgment==='risk')?'risk':report.findings.some(f=>f.judgment==='insufficient')?'warning':'clear';
 return <div className="report-v2">
  <section className={`consumer-result ${tone}`}><span className="result-icon">{tone==='clear'?'✓':tone==='unknown'?'?':'!'}</span><div className="result-copy"><small>{report.status==='complete'?'宣传核验报告':'本次未完成判断'}</small><h1>{report.summary}</h1><p>{report.scope[0]}{report.cached?' · 已复用相同内容报告':''}</p></div><button type="button" onClick={onReset}>检测另一条</button></section>
  {report.findings.length>0&&<section className="report-findings" aria-label="主要发现">{report.findings.map((f,i)=><article key={i}><span className={`finding-label ${f.judgment}`}>{labels[f.judgment]}</span><blockquote>“{f.quote}”</blockquote><p>{f.reason}</p><details><summary>查看依据{f.citations.length?`（${f.citations.length}）`:''}</summary>{f.citations.length?f.citations.map(id=>{const s=report.sources.find(s=>s.id===id)!;return <div className="source-detail" key={id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} · {s.section} ↗</a><p>{s.text}</p><small>{s.version} · 知识库摘要，非产品检测证明</small></div>;}):<p>本次检索没有足够依据支持该具体宣称。</p>}</details></article>)}</section>}
  <section className="report-ingredients"><h2>识别到的成分</h2>{report.ingredients.length?<><p>用途为通用配方角色，不代表成品功效或安全评级。未提供完整配方时不补全。</p><div className="ingredient-table"><table><thead><tr><th>成分 / INCI</th><th>常见用途</th><th>来自哪里</th></tr></thead><tbody>{report.ingredients.map(item=><tr key={item.id}><td><strong>{item.cn}</strong><small>{item.inci}</small></td><td>{item.purpose}</td><td>{item.origin==='label'?'用户标记的标签截图':'内容提及'}<small>“{item.quote}”</small></td></tr>)}</tbody></table></div><details><summary>成分命名来源</summary><a href={report.ingredients[0].source.url} target="_blank" rel="noreferrer">{report.ingredients[0].source.title} ↗</a><p>中文名与用途为人工整理的初版映射；不代表已逐项审核配方合规性。</p></details></>:<p>已取得内容中未识别到已收录成分，不代表产品不含其他成分。</p>}</section>
  <details className="report-scope"><summary>分析范围与已读取内容</summary><ul>{report.scope.map((s,i)=><li key={i}>{s}</li>)}</ul><pre>{text||'尚未取得正文、画面文字或口播。'}</pre>{report.status!=='complete'&&report.sources.length>0&&<><h3>可供参考的资料（尚未形成结论）</h3>{report.sources.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} · {s.section} ↗</a></p>)}</>}</details>
  <footer className="report-footer"><p>{report.note}</p><small>报告 v{report.version} · 知识库 {report.kbVersion}</small><button type="button" onClick={printReport}>打印 / 保存 PDF</button></footer>
 </div>;
}
