import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

// The website and isolated cloud reader must use exactly the same parser.
const root = new URL('../', import.meta.url);
for (const path of ['server/link-resolver', 'shared/links', 'shared/link-page', 'shared/media-url', 'shared/resolution-cache']) {
  const source = await readFile(new URL(`lib/${path}.ts`, root), 'utf8');
  const output = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } }).outputText
    .replace(/(from\s+['"][^'"]+)\.ts(['"])/g, '$1.mjs$2');
  const target = new URL(`ops/cloud-reader/lib/${path}.mjs`, root);
  await mkdir(new URL('./', target), { recursive: true });
  await writeFile(target, '// Generated by scripts/build-reader.mjs; edit lib/ sources.\n' + output);
  console.log(fileURLToPath(target));
}
